apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-generator-plugin-demo
  namespace: argocd
spec:
  generators:
  - plugin:
      configMapRef:
        name: tenant-generator-plugin
      requeueAfterSeconds: 120
      input:
        parameters:
          organization: "demo-corp"
    selector:
      matchExpressions:
        - key: status
          operator: In
          values:
            - trial
            - active
  goTemplate: true
  template:
    metadata:
      name: '{{ .project }}-{{ .environment }}-{{ .tenant | lower | replace "_" "-" }}'
      labels:
        org: 'demo-corp'
        project: '{{ .project }}'
        environment: '{{ .environment }}'
        tenant: '{{ .tenant }}'
    spec:
      project: default
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{ .project }}-{{ .environment }}'
      source:
        chart: '{{ .chart }}'
        repoURL: '{{ .repo_url }}'
        targetRevision: '{{ .target_revision }}'
        helm:
          parameters:
          - name: "fullnameOverride"
            value: '{{ .project }}-{{ .tenant | lower | replace "_" "-" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
